name: Copy dist folder to gh-pages branch
env:
  PUBLISH_DIR: quasar-project/dist/spa/
on:
  push:
    branches:
      - main

jobs:
  copy-dist-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
        submodules: 'recursive'
        fetch-depth: 0

    - name: Checkout the gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        checkout: 'force'
        submodules: 'recursive'
        fetch-depth: 0

    - name: Copy dist folder
      run: cp -r quasar-project/dist/spa/* .

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: devcontainers-universal-2-linux-quasar

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update dist folder"
        push: true